apiVersion: apps/v1
kind: Deployment
metadata:
  name: vms-ui
  labels:
    name: vms-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vms-ui
  template:
    metadata:
      labels:
        app: vms-ui
    spec:
      containers:
      - name: vms-ui
        image: gcr.io/erwindev-vms/vms-ui
        ports: 
          - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 3             
      restartPolicy: Always