export const ATTACHMENT_API_BASE = 'http://localhost:5000/a/api/v1'
export const CONTACT_API_BASE = 'http://localhost:5000/c/api/v1'
export const NOTES_API_BASE = 'http://localhost:5000/n/api/v1'
export const PRODUCT_API_BASE = 'http://localhost:5000/p/api/v1'
export const USER_API_BASE = 'http://localhost:5000/u/api/v1'
export const VENDOR_API_BASE = 'http://localhost:5000/v/api/v1'
